### ISSUE TITLE
headphones_fix

### ISSUE THREAD

**Issue by luxus13** [dreamwhite/dell-inspiron-5370-hackintosh#22]
Hi,
Thank you for your perfect documentation, but I have a question:
I used the headphones_fix, unfortunately this fix doesn't work for me.
The fix does not load although I did everything as described, do you have any idea why the daemon does not start?
best regards

![Bildschirmfoto 2021-03-22 um 11 42 58](https://user-images.githubusercontent.com/68316190/111978222-fbc3ad80-8b03-11eb-884d-695f4bce67ab.png)
![Bildschirmfoto 2021-03-22 um 11 43 22](https://user-images.githubusercontent.com/68316190/111978237-00886180-8b04-11eb-82dd-35320335447c.png)
![Bildschirmfoto 2021-03-22 um 11 44 08](https://user-images.githubusercontent.com/68316190/111978253-041be880-8b04-11eb-9e5f-711b2ea55e27.png)
![Bildschirmfoto 2021-03-22 um 11 44 23](https://user-images.githubusercontent.com/68316190/111978263-054d1580-8b04-11eb-8e3c-042108922b0b.png)

**Comment by luxus13** [comment]
Hi,
have a partial success, when starting the notebook the headphone connection works but when I put the notebook in sleep / wake I have to execute the command alc-verb 0x19 0x707 0x24 and alc-verb 0x1a 0x707 0x20 so that the headphone connection works
best regards

**Comment by dreamwhite** [comment]
Well to be fair, have you edited `alcplugfix_config.plist` so that it executes the command on wake?

Edit [L24](https://github.com/dreamwhite/dell-inspiron-5370-hackintosh/blob/master/headphones_fix/alcplugfix_config.plist#L24) and [L50](https://github.com/dreamwhite/dell-inspiron-5370-hackintosh/blob/master/headphones_fix/alcplugfix_config.plist#L50) so they're enabled and again do the necessary tests. 

Otherwise, if the above solution doesn't work you can disconnect and reconnect the headphone jack so it will reexecute the command. I know that this may be seen as frustrating but even on Linux (Pop!_OS 20.04 just for reference) I had to disconnect and reconnect the headphones. 
I'd highly suggest buying a USB dac ([example](https://www.amazon.it/UGREEN-Adattatore-Microfono-Compatibile-Raspberry/dp/B087T5H3MQ/ref=sr_1_7?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&dchild=1&keywords=ugreen+scheda+audio&qid=1616851088&sr=8-7)) or buying a USB headset, so you don't have any kind of issues with the connect/disconnect stuff :P 

Please let me know if this works for you. I'll keep this issue opened until we found a fix

**Comment by luxus13** [comment]
Hello,
Thanks for your instructions, they were exactly right, now the headphone connection works perfectly even after sleep / wake.
I apologize that I did not read correctly even though you documented everything.
best regards

**Comment by dreamwhite** [comment]
> Hello,
> Thanks for your instructions, they were exactly right, now the headphone connection works perfectly even after sleep / wake.
> I apologize that I did not read correctly even though you documented everything.
> best regards

Fantastic! I'm really glad that this helped you.
I'm going to update `alcplugfix_config.plist` with the edit I suggested you.
Thank you so much and have a nice day
