### ISSUE TITLE
can you use hdmi and type-c to drive 4k display?

### ISSUE THREAD

**Issue by Bradley-Liu** [dreamwhite/dell-inspiron-5370-hackintosh#25]
I have a latitude 5400 and I think it is pretty much the same as yours. I have two 4k displays and i need my hdmi  and typec port to output 4k. I've tried to modify DMVT-pre allocate frome default 0x1(32M) to 0x2 (64M)or 0x3(128M). After I've done that i just got a blue screen when booting into windows with a error msg of "acpi bios error" and I can't boot into mac os either. Do you have any idear as for what's going on. Have you tried 4k output of your hdmi port or dp port?
Thank you!

**Comment by dreamwhite** [comment]
> I have a latitude 5400 and I think it is pretty much the same as yours. I have two 4k displays and i need my hdmi and typec port to output 4k. I've tried to modify DMVT-pre allocate frome default 0x1(32M) to 0x2 (64M)or 0x3(128M). After I've done that i just got a blue screen when booting into windows with a error msg of "acpi bios error" and I can't boot into mac os either. Do you have any idear as for what's going on. Have you tried 4k output of your hdmi port or dp port?
> Thank you!

Thank you so much for reaching me there. Well to be fair on my side 4K output works both from HDMI and USB-C port but probably this is due to different model of laptops. I don't know what are your laptop specs, neither what kind of EFI you're running >_>
I highly suggest you to ask on InsanelyMac or macos86.it if anyone has the same laptop or eventually how to proceed :)
