### ISSUE TITLE
Shortcuts Brightness keys

### ISSUE THREAD

**Issue by luxus13** [dreamwhite/dell-inspiron-5370-hackintosh#9]
Hi there
Thank you for all of your efforts.
Thanks to you, my 5370 runs perfectly

I just can't understand one point
Brightness keys:
You wrote: so I've simply mapped them inside SysPrefs / Keyboard / Shortcuts
How can I assign shortcuts to these keys?

best regards

**Comment by dreamwhite** [comment]
Hi, thank you so much for reaching me out on my repository. Regarding to your attention, basically my laptop has a Fn-lock which basically allows you use fn-keys (like multimedia keys) just by pressing them without pressing fn.
If you want to press F1, for example, you'll need to press fn+F1.

Since the brightness keys aren't working smoothly I decided to map them as fn-F11 and fn-F12.
If you don't see "Display" in System Preferences/Keyboard, attach a USB keyboard and it will appear.

I'll leave this issue opened until you manage to fix it ^^

**Comment by luxus13** [comment]
Hello
I can only say, thank you, Your proposal with the external keyboard was the solution.
everything, absolutely everything runs 100%
I already use the latest Kext as well as OC 0.6.5.
You saved me a lot of time.
Best regards

**Comment by dreamwhite** [comment]
> Hello
> I can only say, thank you, Your proposal with the external keyboard was the solution.
> everything, absolutely everything runs 100%
> I already use the latest Kext as well as OC 0.6.5.
> You saved me a lot of time.
> Best regards

Fantastic! Many thanks you too. Hope you enjoyed the repository ^^
Best regards you too anche have nice holidays
